- name: Hello world
  hosts: web
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello World!"
      
  - name: install nginx
    ansible.buildin.package:
      name: nginx
      state: present
