- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with aws"
    DURATION: "140hrs"
    TRAINER: "siva reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} , trainer is {{ TRAINER }}"
      