- name: demo on conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: true
  tasks: 
  - name: conditions  check live or not
    ansible.builtin.debug:
      msg: "yes"
    when: IS_LIVE
