- name: demo of filters
  hosts: local
  connection: local
  become: yes
  vars:
    topics: linux , shell , ansible , terraform
  tasks:
  - name: filter files_output
    ansible.builtin.debug:
      msg: "Hi Sivakumar , {{ GREETING | default('good morning') }}" # it is a default value used to place a default input in case

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{topics | split(',')}}"